export type PlantProps = {
  id: string;
  name_pe: string;
  name_en: string;
  price: number;
  picture: string;
  category: string;
  type: string;
  plant: string;
  maintain_st_pe: string;
  maintain_st_pe_value: string;
  maintain_st_en: string;
  maintain_st_en_value: string;
  maintain_nd_pe: string;
  maintain_nd_pe_value: string;
  maintain_nd_en: string;
  maintain_nd_en_value: string;
  maintain_rd_pe: string;
  maintain_rd_pe_value: string;
  maintain_rd_en: string;
  maintain_rd_en_value: string;
  maintain_th_pe: string;
  maintain_th_pe_value: string;
  maintain_th_en: string;
  maintain_th_en_value: string;
};
